#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : {{ cookiecutter.book_name }}  # The title of the book. Will be placed in the left navbar.
author                      : {{ cookiecutter.author_name }}  # The author of the book
copyright                   : "{% now 'local', '%Y' %}"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo